development: &common
  adapter: postgresql
  encoding: unicode
  database: schedulesavvy_development
  pool: 5
  username:
  password:

test: &test
  <<: *common
  database: schedulesavvy_test

production:
  <<: *common
  database: schedulesavvy_production

# Matching environments specified in this file will override the above
<%= IO.read("config/database.local.yml") if File.exists?("config/database.local.yml") %>

cucumber:
  <<: *test